services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: stop-motion-app
    stdin_open: true
    ports:
      - "${DOCKER_COMPOSE_APP_PORT_PUBLISHED:-4200}:4200"
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules:cached
