#!/usr/bin/env node
// Generate NOTICES.txt: every third-party runtime dependency bundled into the
// StopClip distribution, with its license text. Re-run after dependency
// upgrades: `pnpm run generate:notices`.

import { readFile, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const MODULES = join(ROOT, 'node_modules')
const OUTPUT = join(ROOT, 'NOTICES.txt')

// devDependencies whose code ships in the production artifact even though
// they're listed under devDependencies (build-time tools that emit runtime
// payloads). Add to this list if Vite/Workbox ever pull additional runtimes
// into the bundle.
const SHIPPED_DEV_DEPS = ['workbox-window']

const LICENSE_FILENAMES = [
  'LICENSE',
  'LICENSE.md',
  'LICENSE.txt',
  'LICENCE',
  'LICENCE.md',
  'LICENCE.txt',
  'license',
  'license.md',
]

async function readJson(path) {
  return JSON.parse(await readFile(path, 'utf8'))
}

async function findLicenseText(pkgDir) {
  for (const name of LICENSE_FILENAMES) {
    const candidate = join(pkgDir, name)
    if (existsSync(candidate)) {
      const text = (await readFile(candidate, 'utf8')).trim()
      return { filename: name, text }
    }
  }
  return null
}

function repoUrl(pkg) {
  if (!pkg.repository) return null
  const raw =
    typeof pkg.repository === 'string'
      ? pkg.repository
      : pkg.repository.url || null
  if (!raw) return null
  return raw
    .replace(/^git\+/, '')
    .replace(/^git:\/\//, 'https://')
    .replace(/^git@([^:]+):/, 'https://$1/')
    .replace(/\.git$/, '')
}

function authorString(pkg) {
  if (!pkg.author) return null
  if (typeof pkg.author === 'string') return pkg.author
  if (pkg.author.name) return pkg.author.name
  return null
}

async function describePackage(name) {
  const pkgDir = join(MODULES, name)
  if (!existsSync(pkgDir)) {
    return { name, missing: true }
  }
  const pkg = await readJson(join(pkgDir, 'package.json'))
  const license = await findLicenseText(pkgDir)
  return {
    name,
    version: pkg.version,
    license: pkg.license ?? null,
    repository: repoUrl(pkg) ?? pkg.homepage ?? null,
    author: authorString(pkg),
    licenseFilename: license?.filename ?? null,
    licenseText: license?.text ?? null,
  }
}

function formatEntry(entry) {
  const divider = '='.repeat(80)
  const lines = [divider, `${entry.name}@${entry.version}`]
  if (entry.license) lines.push(`License: ${entry.license}`)
  if (entry.author) lines.push(`Author: ${entry.author}`)
  if (entry.repository) lines.push(`Source: ${entry.repository}`)
  lines.push('')
  if (entry.licenseText) {
    lines.push(entry.licenseText)
  } else {
    lines.push(
      `(No LICENSE file was published in the ${entry.name} npm tarball. ` +
        `Refer to the upstream repository for the full license text.)`,
    )
  }
  lines.push('')
  return lines.join('\n')
}

async function main() {
  const rootPkg = await readJson(join(ROOT, 'package.json'))
  const runtimeDeps = Object.keys(rootPkg.dependencies ?? {})
  const shipped = [...runtimeDeps, ...SHIPPED_DEV_DEPS]
  const unique = [...new Set(shipped)].sort()

  const entries = []
  for (const name of unique) {
    entries.push(await describePackage(name))
  }

  const header = [
    'NOTICES',
    '',
    'This file lists every third-party dependency bundled into the StopClip',
    'production distribution, together with the full text of each license.',
    '',
    'StopClip itself is licensed under the GNU Affero General Public License',
    'v3.0 or later (AGPL-3.0-or-later); see LICENSE. The dependency licenses',
    'recorded below (MIT, BSD-3-Clause and MPL-2.0) are compatible with',
    'redistribution under those terms. MPL-2.0 is a file-level (weak) copyleft',
    'license; under MPL-2.0 §3.3 its files may be combined into this AGPL-3.0',
    'work, provided those files keep their MPL-2.0 notices.',
    '',
    'This file is auto-generated by scripts/generate-notices.mjs from',
    'package.json and each dependency\'s published LICENSE file. Re-run after',
    'upgrading or adding dependencies: `pnpm run generate:notices`.',
    '',
    `Generated: ${new Date().toISOString().slice(0, 10)}`,
    '',
  ].join('\n')

  const body = entries.map(formatEntry).join('\n')
  const footer =
    '\n' +
    '='.repeat(80) +
    '\n' +
    'For the StopClip source license (AGPL-3.0-or-later) see LICENSE.\n'

  await writeFile(OUTPUT, header + '\n' + body + footer, 'utf8')

  const missing = entries.filter((e) => e.missing).map((e) => e.name)
  const noLicense = entries
    .filter((e) => !e.missing && !e.licenseText)
    .map((e) => e.name)

  process.stdout.write(`Wrote ${OUTPUT} with ${entries.length} dependencies.\n`)
  if (missing.length) {
    console.warn(`Warning: not installed in node_modules: ${missing.join(', ')}`)
  }
  if (noLicense.length) {
    console.warn(
      `Warning: no LICENSE file in npm tarball for: ${noLicense.join(', ')}`,
    )
  }
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
